#此为选择注册配置中心
registration:
  center:
    type: nacos # 或 zookeeper
    server-addr: localhost:8848

#此为nacos路由配置的相关属性
nacos:
  ip: 127.0.0.1
  port: 8848
  dataId: 2
  group: route2

#此为zookeeper路由配置的相关属性
zookeeper:
  ip: ""
  port: ""


#配置netty所监听的端口
netty:
  port: 10001
  times: 3
  maxQps: 1000 # 全局最大QPS
  serviceTokenRefillRate: 200 # 服务令牌桶每秒填充速率
  serviceMaxBurst: 500 # 服务令牌桶容量
  userTokenRefillRate: 200
  userMaxBurst: 500
  noUserTokenRefillRate: 200
  noUserMaxBurst: 500
